// Package docs Code generated by swag. DO NOT EDIT.
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/users": {
            "get": {
                "description": "Returns all users",
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "List all users",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": { "$ref": "#/definitions/models.User" }
                        }
                    }
                }
            },
            "post": {
                "description": "Creates a new user and publishes a user.created event",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Create a new user",
                "parameters": [
                    {
                        "description": "Create user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.CreateUserRequest" }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": { "$ref": "#/definitions/models.User" }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/users/{id}": {
            "get": {
                "description": "Returns a single user",
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Get a user by ID",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": { "$ref": "#/definitions/models.User" }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            },
            "put": {
                "description": "Updates a user and publishes a user.updated event",
                "consumes": ["application/json"],
                "produces": ["application/json"],
                "tags": ["users"],
                "summary": "Update an existing user",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Update user request",
                        "name": "request",
                        "in": "body",
                        "required": true,
                        "schema": { "$ref": "#/definitions/models.UpdateUserRequest" }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": { "$ref": "#/definitions/models.User" }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        },
        "/health": {
            "get": {
                "description": "Returns service health status",
                "produces": ["application/json"],
                "tags": ["health"],
                "summary": "Health check",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": { "type": "object", "additionalProperties": { "type": "string" } }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.User": {
            "type": "object",
            "properties": {
                "id":         { "type": "string" },
                "email":      { "type": "string" },
                "name":       { "type": "string" },
                "created_at": { "type": "string" },
                "updated_at": { "type": "string" }
            }
        },
        "models.CreateUserRequest": {
            "type": "object",
            "required": ["email", "name"],
            "properties": {
                "email": { "type": "string", "example": "john@example.com" },
                "name":  { "type": "string", "example": "John Doe" }
            }
        },
        "models.UpdateUserRequest": {
            "type": "object",
            "properties": {
                "email": { "type": "string", "example": "john@example.com" },
                "name":  { "type": "string", "example": "John Doe" }
            }
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it.
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{"http"},
	Title:            "Event-Driven User API",
	Description:      "A RESTful API that publishes user events to RabbitMQ for async processing by CRM and Analytics consumers.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
